language: go
go:
- 1.13.x
- 1.12.x
- 1.11.x
script:
- make test
dd:
  secure: b6WpbvuCVQ9YXgmGlHC52tMVyN5r2HbSmfjqyDDXrk10R9rBnTapk6RqTMoxS/DJUlewJkISWs3tUlp0453wz+Oud0gChLLI9Mf0si5QUCo58b7YAWk4iE3uqneCVymOAKe3XGP4Djc9Uz4z4Goi0Wt+5uQ8A6Eu5xL3LaovRwJLf0hb5puRuX8FtZsW6MtgsdnickZSyH5TNP8MqMn9lNjxdXLjUUx1f7nArM38isk3jy7QMqZhFncvb7C9ujEqjoGckJqj7FBkv4/n1PFBWPQcanHRQ7XRLMzom0gImWntYXmMpaW+fUEMfwV+8WjEX7VGzb8ZsAZzeka8+m+E+cyez1TA34pCx0XCbt+U7Za7LytKcV8pcN12YaQ9BCKmWKMlq4hgZoEFSS8EnhVUKBiYBnHtFDqQdZh2RPSo828TxNqqFa4OG7fT8U1z25Raexj1e5eTZ8JV6Tq3UOVOHzfm1TOkfoI+YRZ2FtHHy7Ts3m9lI2iUSfynzRJSTMYkRIKm5TL/L+W7sVJby+LYXaKEJzd+nOK0RtGSWdwpIb2gKlTNMr5P7Q3bd/IOsMQhxk+e7QoL5U4RjcSi17alQ+/c0PaK78lSfvo2YIhB6EjixKehAvIPbNhccG9KA+KUPJ8LKZc7uJivH00KPZfD3NIDynyYtYmK/NLFgwcinsU=
